production:
  environment: production
  production_environment: true

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false

review:
  environment: pr${{ pr }}
  transient_environment: true
  production_environment: false

review2:
  required_contexts: [build]
  environment: test
  transient_environment: true
  production_environment: false
