name: Github Action Push Test

on:
  push:
    tags:
      - 'v*'
    branches:
      - test/pr

jobs:
  tag-build:
    name: tag-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: if
        if: github.event.ref_type == 'tag'
        run: |
          echo 'hello'